### ISSUE TITLE
Make a QA list to query 

### ISSUE THREAD

**Issue by jstout211** [jstout211/enigma_MEG#12]
- [x] QA list will be empty
- [x] Upon review - the  classification will be unchecked
- [x] After the next/final button is selected - change to good/bad
- [x] Write good/bad to QA text file

**Comment by jstout211** [comment]
using py logging - setup 

- [ ] Log type (fsrecon, parcels, etc)
- [ ] load logger and check for previously reviewed
- [ ] save outputs to logger upon gui close

**Comment by nugenta** [comment]
Pressing exit on the GUI now saves. Should the save button be removed? There are now individual logs for each QA type

**Comment by jstout211** [comment]
@nugenta  -- For large studies people might still want to save incrementally in case something errors out  (I know this will never happen though ...).

**Comment by nugenta** [comment]
Can we close this one out then?
