### ISSUE TITLE
Initalization - Logfile Parse

### ISSUE THREAD

**Issue by jstout211** [jstout211/enigma_MEG#16]
Read previous logfile
Parse the last time 
Readout all of the subject status items into a dictionary
During subject initialization - reference the history dictionary to pull status and initialize button color

**Comment by jstout211** [comment]
The above has been added here: bcc896cdc261ac2a79ad363aa9b77e07affd9cda
Parsing of the logfile - needs to ignore the current field if nothing was saved

**Comment by nugenta** [comment]
I believe that this can be closed because now subject status is saved upon exit of the GUI
