### ISSUE TITLE
Create QA images using MNE Report

### ISSUE THREAD

**Issue by jstout211** [jstout211/enigma_MEG#3]
In the final process_meg function:
Write raw-cov.fif
Write eroom-cov.fif
Write -trans.fif 
Write downsampled...fif

from mne import Report

#Run the following to collect and write out the QA files
report = Report(image_format='png', subjects_dir=subjects_dir,
               subject='APBWVFAR_fs_ortho', info_fname='APBWVFAR_300fs_meg.fif', 
                raw_psd=False)  # use False for speed here

meg_path = '/home/stoutjd/data/DEMO_ENIGMA/outputs/APBWVFAR_fs_ortho'
report.parse_folder(meg_path, on_error='ignore', mri_decim=10)
report.save('outfile.html')

**Comment by nugenta** [comment]
Images are now created as .png files which can be assessed using the QA GUI - this may be more useful, but I'm not opposed to also creating the MNE report. Thoughts?

**Comment by nugenta** [comment]
For the moment, .png files to be assessed with the QA GUI are sufficient, if a MNE report is necessary for some reason open a new issue.
